version: '3'
services:
  flower:
    image: flower:b0e6aaf73c3121798ae9e3fef11e97ea6f609797
    command: celery flower --address=0.0.0.0 --port=5555 --loglevel=info --url_prefix=flower
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
    
  redis:
    image: redis:latest
